language: ruby
bundler_args: --without debug
rvm:
  - 1.9.3
  - 1.9.2
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
#  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
notifications:
  email:
    - sk@semicolon.at
  on_success: change
  on_failure: always
