language: ruby
bundler_args: --without debug
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-head
  - rbx
  - 1.9.2
  - 1.8.7
  - ree
notifications:
  email:
    - sylvester@keil.or.at
  on_success: change
  on_failure: always
